### ISSUE TITLE
Межстрочный интервал

### ISSUE THREAD

**Issue by mivallion** [glumpo/mai_prac_2017#1]
В книге кажется более крупный межстрочный интервал. Так же не совпадают переносы строк и возможно размер шрифта. Насчет последнего не уверен, насчет переносов - расставлять ручками переносы или это фиксится нормальным путем?

**Comment by mivallion** [comment]
+ Слишком маленькие формулы получаются, в книге они явно больше (по крайней мере те, что прямо в тексте вставлены)

**Comment by HagRead-Only** [comment]
Вчера вечером в разговоре с Валентином Евгеньевичем мы благополучно сошлись на мнении, что до маразма доводить аутентичность не надо, ибо мы не верстаем точную копию издания для типографии. Более того, даже количество страниц и объем текста на них могут не совпадать (например, из-за вставок собственных фрагментов кода, которые могут отличаться по размерам).
По поводу межстрочных интервалов: да, вероятно я бы тоже малость увеличил, чтобы формулам внутри текста не было тесно.
На остальное можно не обращать внимания ввиду несущественности. Если вдруг случится нечто и Зайцева что-то не устроит, при мердже поправим. Или обновим .cls-файл. Это не проблема.

Вот две пикчи для сравнения, чтобы были:
_(Оригинал)_
![image](https://user-images.githubusercontent.com/12846931/27909352-e618bdcc-6258-11e7-9019-86840fa5f7c9.png)
_(TeX)_
![image](https://user-images.githubusercontent.com/12846931/27909295-ac4d7286-6258-11e7-9acd-1f0cd7dd7da5.png)

@glumpo Решай, что делать что c межстрочным интервалом, потом можно закрывать issue, я считаю.

**Comment by glumpo** [comment]
Обсуждали межстрочный интервал, поблема в том, что на большем интервале некоторым режет глаз слишком размазаный текст. То есть есть два стула, надо решить, на какой сядем. Думаю, пока вопрос не горит, можно и постоять. Со следующим коммитом увеличу интервал в классе, посморим на реакцию общественности. Про остальное - после сегодняшнего разговора с Валентином Евгеньевичем, пришел к выводу, что каких-то конкретных требований нет. Должно быть нормально сверстано, должо быть переписано на си. Остальное - как решим сделать, так и сделаем. Разумеется, перебивать страница в страницу - бред, поэтому стоит приблизительно ориентироваться на оригинальную разбивку, но без фанатизма.

Что касается формул - не знаю, в чем может быть причина, погляжу, может получится сделать лучше, но сильно менять не буду, чтобы уже готовая верстка не полетела. Обратная совместимость приоритетнее. Но интервал - попробую пофиксить.
