### ISSUE TITLE
Доказательства, замечания

### ISSUE THREAD

**Issue by mivallion** [glumpo/mai_prac_2017#2]
Замечания не поддерживают сноски через footnote
Доказательства с замечаниями очень странно занимают пространство
![screenshot from 2017-07-09 18-04-05](https://user-images.githubusercontent.com/24232546/27995087-265e0db8-64d1-11e7-94c1-9d32244db72c.png)
Нумерацию для теорем-предложений и тд сделать бы как в книге - в начале и в скобках напр. (21) предложение. И как проставить счетчик для них?

**Comment by glumpo** [comment]
Про footnote. Можно код? Не могу воспроизвести баг.





![2017-07-09 19-13-27](https://user-images.githubusercontent.com/9488033/27995683-2f3a5f0e-64db-11e7-861d-dfbd898e74db.png)
![2017-07-09 19-13-40](https://user-images.githubusercontent.com/9488033/27995687-3418644e-64db-11e7-884c-4499727e4f77.png)

**Comment by glumpo** [comment]
Про счетчик - вручную ставить необходимости нет. Когда будем верстать в один файл - все счетчики встанут на свои места. Потому стоит вообще избегать их использования, это костыль, необходимость в котором пропала.

**Comment by glumpo** [comment]
Про место. Согласен на счет доказательств, посмотрю, что с этим можно сделать и как лучше поменять, чтобы верстка у ледей не слиьно съехала. Про замечание - мне кажется, вполне нормально занимает место. Хотя, обсудить стоит.

**Comment by glumpo** [comment]
Вообще, появилась такая мысль, ты \pagebreak не юзал? Он мог растянуть тебе страницу основательно. Если использовал, поменяй на \newpage. Или кинь код, так по скринам не особо видно.
Да и в следующи раз открывай иссуе для каждой ошибки. Так просто удобнее.
