### ISSUE TITLE
Caption separator

### ISSUE THREAD

**Issue by darkloned** [glumpo/mai_prac_2017#3]
Set dot instead of colon in captions.

**Comment by glumpo** [comment]
Лол, у нас, кажется, ошибка. Какая неожиданность.

**Comment by HagRead-Only** [comment]
![image](https://user-images.githubusercontent.com/12846931/28193176-73174cda-6843-11e7-9e6d-5b82936b7618.png)

**Comment by glumpo** [comment]
Ахах, ну да, типо того. Думаю, теперь ошибку можно закрывать. Хотя, если есть желание, можешь пофиксить.

**Comment by HagRead-Only** [comment]
I don't care now either ;)

**Comment by glumpo** [comment]
А как же прокуратура? Придет дядя в погонах и скажет, чому у вас тут caption не аутентичный, ммм?
